### ISSUE TITLE
发消息没反应

### ISSUE THREAD

**Issue by dclemon** [ColdRain-Moro/ChatGPT-qq-bot#1]
![image](https://user-images.githubusercontent.com/63597032/216801013-831351c5-ca97-45e3-a516-669ec9b8dc8e.png)
token也填了，只能接受消息

**Comment by hiyasame** [comment]
用的是爬虫，不是官方API。官方上了cloudflare之后就用不了了

**Comment by hiyasame** [comment]
我刚刚更新了一下 最新版本可以用了 不过token得换成官方的api key

**Comment by dclemon** [comment]
> 我刚刚更新了一下 最新版本可以用了 不过token得换成官方的api key
我是用docker部署的，貌似镜像也需要更新一下
